name: Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/adrinator_site/"

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email "adrianorodriguesdsousa@ufpi.edu.br"
          git config --global user.name "Adriano R. de Sousa"
          git status
          git remote add origin https://${{secrets.ADRINATOR_DEPLOY}}@github.com/certainlyWrong/adrinator_site.git
          git checkout -b gh-pages
          git add --all
          git commit -m ":rocket: Update"
          git push origin gh-pages -f
